name: two-photon
channels:
  - conda-forge
dependencies:
  - python=3.10
  - mkl
  - mkl_fft
  - tbb
  - numpy
  - numba
  - matplotlib
  - scipy
  - scikit-learn
  - click
  - click-option-group
  - pandas
  - pytables
  - tifffile
  - pip  # Keep pip here, but move package installs to Dockerfile
